"""Complete 78-card Tarot deck data (韦特塔罗).

包含22张大阿卡纳和56张小阿卡纳（4花色 x 14张）的完整数据。
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# 牌阵配置
# ---------------------------------------------------------------------------

SPREADS: dict[str, dict] = {
    "single": {
        "name": "单牌",
        "count": 1,
        "description": "直觉指引，适合每日运势或快速解答",
        "positions": ["指引牌"],
    },
    "three": {
        "name": "三牌阵",
        "count": 3,
        "description": "过去→现在→未来",
        "positions": ["过去", "现在", "未来"],
    },
    "love": {
        "name": "爱情三角",
        "count": 3,
        "description": "感情关系分析",
        "positions": ["你", "对方", "关系走向"],
    },
    "choice": {
        "name": "二选一",
        "count": 5,
        "description": "面临选择时使用",
        "positions": [
            "现状",
            "选项A-过程",
            "选项A-结果",
            "选项B-过程",
            "选项B-结果",
        ],
    },
    "horseshoe": {
        "name": "马蹄铁",
        "count": 7,
        "description": "事业/决策深度分析",
        "positions": ["过去", "现在", "未来", "建议", "环境", "希望", "结果"],
    },
    "hexagram": {
        "name": "六芒星",
        "count": 7,
        "description": "综合运势分析",
        "positions": ["过去", "现在", "未来", "建议", "环境", "潜意识", "结果"],
    },
    "celtic": {
        "name": "凯尔特十字",
        "count": 10,
        "description": "最全面的深度分析牌阵",
        "positions": [
            "现状",
            "挑战(交叉)",
            "潜意识基础",
            "近期过去",
            "可能结果",
            "近期未来",
            "自我认知",
            "外部影响",
            "希望/恐惧",
            "最终结果",
        ],
    },
    "life_tree": {
        "name": "生命之树",
        "count": 10,
        "description": "灵性成长与自我探索",
        "positions": [
            "王冠(灵性)",
            "智慧",
            "理解",
            "慈悲",
            "力量",
            "美(和谐)",
            "胜利",
            "荣耀",
            "基础",
            "王国(现实)",
        ],
    },
}

# ---------------------------------------------------------------------------
# 22 Major Arcana (大阿卡纳)
# ---------------------------------------------------------------------------

MAJOR_ARCANA: list[dict] = [
    {
        "number": 0,
        "name": "愚者",
        "name_en": "The Fool",
        "upright": "新开始、冒险、自由、纯真、无限可能",
        "reversed": "鲁莽、冒失、不计后果、缺乏方向",
        "element": "风",
        "planet": "天王星",
        "keywords": ["新起点", "信仰飞跃", "天真"],
    },
    {
        "number": 1,
        "name": "魔术师",
        "name_en": "The Magician",
        "upright": "创造力、意志力、技能、资源充足、自信",
        "reversed": "操控、欺骗、才能未发挥、缺乏自信",
        "element": "风",
        "planet": "水星",
        "keywords": ["创造", "行动力", "掌控"],
    },
    {
        "number": 2,
        "name": "女祭司",
        "name_en": "The High Priestess",
        "upright": "直觉、潜意识、内在智慧、神秘、耐心等待",
        "reversed": "忽视直觉、表面化、秘密暴露、过度依赖理性",
        "element": "水",
        "planet": "月亮",
        "keywords": ["直觉", "内在声音", "奥秘"],
    },
    {
        "number": 3,
        "name": "女皇",
        "name_en": "The Empress",
        "upright": "丰饶、母性、自然、感官享受、创造力",
        "reversed": "依赖、过度保护、创造力枯竭、忽视自我",
        "element": "土",
        "planet": "金星",
        "keywords": ["丰盛", "滋养", "生命力"],
    },
    {
        "number": 4,
        "name": "皇帝",
        "name_en": "The Emperor",
        "upright": "权威、结构、稳定、领导力、纪律",
        "reversed": "专制、僵化、控制欲过强、缺乏弹性",
        "element": "火",
        "planet": "白羊座",
        "keywords": ["权威", "秩序", "掌控"],
    },
    {
        "number": 5,
        "name": "教皇",
        "name_en": "The Hierophant",
        "upright": "传统、信仰、教育、指导、精神追求",
        "reversed": "打破常规、教条主义、反叛传统、自学成才",
        "element": "土",
        "planet": "金牛座",
        "keywords": ["传承", "信仰", "导师"],
    },
    {
        "number": 6,
        "name": "恋人",
        "name_en": "The Lovers",
        "upright": "爱情、和谐、关系选择、价值观契合、吸引力",
        "reversed": "不和谐、价值观冲突、错误选择、自我矛盾",
        "element": "风",
        "planet": "双子座",
        "keywords": ["爱情", "选择", "结合"],
    },
    {
        "number": 7,
        "name": "战车",
        "name_en": "The Chariot",
        "upright": "胜利、意志力、决心、掌控方向、克服障碍",
        "reversed": "失控、方向迷失、攻击性、缺乏自律",
        "element": "水",
        "planet": "巨蟹座",
        "keywords": ["前进", "征服", "决心"],
    },
    {
        "number": 8,
        "name": "力量",
        "name_en": "Strength",
        "upright": "勇气、内在力量、耐心、柔中带刚、自我掌控",
        "reversed": "自我怀疑、软弱、缺乏自信、用蛮力",
        "element": "火",
        "planet": "狮子座",
        "keywords": ["内在力量", "勇气", "温柔"],
    },
    {
        "number": 9,
        "name": "隐者",
        "name_en": "The Hermit",
        "upright": "内省、独处、寻找真理、精神导师、智慧",
        "reversed": "孤立、逃避现实、过度封闭、拒绝帮助",
        "element": "土",
        "planet": "处女座",
        "keywords": ["内省", "独处", "觉悟"],
    },
    {
        "number": 10,
        "name": "命运之轮",
        "name_en": "Wheel of Fortune",
        "upright": "转折点、好运、命运变化、周期循环、机遇",
        "reversed": "厄运、抗拒改变、运势低迷、打破循环",
        "element": "火",
        "planet": "木星",
        "keywords": ["转变", "机遇", "命运"],
    },
    {
        "number": 11,
        "name": "正义",
        "name_en": "Justice",
        "upright": "公正、真相、因果、法律、平衡",
        "reversed": "不公正、逃避责任、偏见、失衡",
        "element": "风",
        "planet": "天秤座",
        "keywords": ["公正", "因果", "真相"],
    },
    {
        "number": 12,
        "name": "倒吊人",
        "name_en": "The Hanged Man",
        "upright": "牺牲、新视角、等待、放下、顺其自然",
        "reversed": "拖延、无谓牺牲、固执己见、抗拒改变",
        "element": "水",
        "planet": "海王星",
        "keywords": ["暂停", "换角度", "臣服"],
    },
    {
        "number": 13,
        "name": "死神",
        "name_en": "Death",
        "upright": "结束、转变、放下旧事物、重生、蜕变",
        "reversed": "抗拒改变、恐惧结束、停滞不前、执念",
        "element": "水",
        "planet": "天蝎座",
        "keywords": ["结束", "重生", "蜕变"],
    },
    {
        "number": 14,
        "name": "节制",
        "name_en": "Temperance",
        "upright": "平衡、耐心、调和、中庸之道、和谐",
        "reversed": "失衡、过度、缺乏耐心、极端行为",
        "element": "火",
        "planet": "射手座",
        "keywords": ["平衡", "调和", "适度"],
    },
    {
        "number": 15,
        "name": "恶魔",
        "name_en": "The Devil",
        "upright": "束缚、欲望、物质主义、执念、诱惑",
        "reversed": "解脱、打破束缚、面对阴暗面、恢复自由",
        "element": "土",
        "planet": "摩羯座",
        "keywords": ["束缚", "欲望", "阴影"],
    },
    {
        "number": 16,
        "name": "高塔",
        "name_en": "The Tower",
        "upright": "突变、崩塌、觉醒、摧毁虚假、解放",
        "reversed": "恐惧改变、苟延残喘、延迟崩塌、内在动荡",
        "element": "火",
        "planet": "火星",
        "keywords": ["突变", "破坏", "觉醒"],
    },
    {
        "number": 17,
        "name": "星星",
        "name_en": "The Star",
        "upright": "希望、灵感、宁静、重获信心、祝福",
        "reversed": "失去希望、悲观、缺乏信心、与灵性脱节",
        "element": "风",
        "planet": "水瓶座",
        "keywords": ["希望", "治愈", "灵感"],
    },
    {
        "number": 18,
        "name": "月亮",
        "name_en": "The Moon",
        "upright": "幻觉、直觉、潜意识、恐惧、不确定",
        "reversed": "克服恐惧、真相浮现、走出迷雾、理性回归",
        "element": "水",
        "planet": "双鱼座",
        "keywords": ["迷惑", "直觉", "潜意识"],
    },
    {
        "number": 19,
        "name": "太阳",
        "name_en": "The Sun",
        "upright": "快乐、成功、活力、光明、乐观",
        "reversed": "暂时受挫、过度乐观、自负、快乐延迟",
        "element": "火",
        "planet": "太阳",
        "keywords": ["光明", "喜悦", "成功"],
    },
    {
        "number": 20,
        "name": "审判",
        "name_en": "Judgement",
        "upright": "觉醒、重生、召唤、反思过去、重大决定",
        "reversed": "自我怀疑、逃避审视、拒绝改变、遗憾",
        "element": "火",
        "planet": "冥王星",
        "keywords": ["觉醒", "审视", "重生"],
    },
    {
        "number": 21,
        "name": "世界",
        "name_en": "The World",
        "upright": "圆满、成就、整合、旅行、目标达成",
        "reversed": "未完成、缺乏闭合感、延迟满足、短视",
        "element": "土",
        "planet": "土星",
        "keywords": ["圆满", "完成", "整合"],
    },
]

# ---------------------------------------------------------------------------
# 花色定义
# ---------------------------------------------------------------------------

SUITS: dict[str, dict] = {
    "wands": {
        "name": "权杖",
        "element": "火",
        "theme": "行动/事业/创造力/激情",
    },
    "cups": {
        "name": "圣杯",
        "element": "水",
        "theme": "情感/关系/直觉/内心",
    },
    "swords": {
        "name": "宝剑",
        "element": "风",
        "theme": "思维/沟通/冲突/真相",
    },
    "pentacles": {
        "name": "金币",
        "element": "土",
        "theme": "物质/财务/健康/实际",
    },
}

# ---------------------------------------------------------------------------
# 56 Minor Arcana (小阿卡纳) - 4 suits x 14 cards
# ---------------------------------------------------------------------------

MINOR_ARCANA: dict[str, list[dict]] = {
    # ===== 权杖 (Wands) - 火 =====
    "wands": [
        {
            "rank": "A",
            "name": "权杖王牌",
            "name_en": "Ace of Wands",
            "upright": "灵感、新机遇、创造力爆发、潜力、开端",
            "reversed": "延迟、缺乏动力、错失机会、创意枯竭",
            "keywords": ["灵感", "新开始", "创造力"],
        },
        {
            "rank": "2",
            "name": "权杖二",
            "name_en": "Two of Wands",
            "upright": "计划、决策、展望未来、掌控全局、远见",
            "reversed": "犹豫不决、恐惧未知、缺乏计划、目光短浅",
            "keywords": ["计划", "远见", "抉择"],
        },
        {
            "rank": "3",
            "name": "权杖三",
            "name_en": "Three of Wands",
            "upright": "拓展、远行、进展顺利、等待回报、前景光明",
            "reversed": "受阻、延迟、视野狭窄、回报未至",
            "keywords": ["拓展", "等待", "远方"],
        },
        {
            "rank": "4",
            "name": "权杖四",
            "name_en": "Four of Wands",
            "upright": "庆祝、和谐、家庭幸福、里程碑、安定",
            "reversed": "不稳定、缺乏支持、过渡期、家庭矛盾",
            "keywords": ["庆祝", "稳定", "归属"],
        },
        {
            "rank": "5",
            "name": "权杖五",
            "name_en": "Five of Wands",
            "upright": "竞争、冲突、分歧、挑战、切磋",
            "reversed": "避免冲突、内在矛盾、妥协、团队协作",
            "keywords": ["竞争", "挑战", "冲突"],
        },
        {
            "rank": "6",
            "name": "权杖六",
            "name_en": "Six of Wands",
            "upright": "胜利、荣誉、公众认可、自信、成就",
            "reversed": "名誉受损、自负、缺乏认可、跌落神坛",
            "keywords": ["胜利", "荣誉", "认可"],
        },
        {
            "rank": "7",
            "name": "权杖七",
            "name_en": "Seven of Wands",
            "upright": "坚守立场、防御、勇气、坚持信念、抵抗",
            "reversed": "退让、不堪重负、信念动摇、放弃",
            "keywords": ["坚守", "防御", "勇气"],
        },
        {
            "rank": "8",
            "name": "权杖八",
            "name_en": "Eight of Wands",
            "upright": "快速进展、行动力、消息传来、旅行、势如破竹",
            "reversed": "延误、混乱、仓促行事、方向不明",
            "keywords": ["迅速", "行动", "进展"],
        },
        {
            "rank": "9",
            "name": "权杖九",
            "name_en": "Nine of Wands",
            "upright": "坚韧、毅力、最后防线、警惕、经验",
            "reversed": "疲惫不堪、固执、偏执、放弃坚守",
            "keywords": ["坚韧", "警觉", "坚持"],
        },
        {
            "rank": "10",
            "name": "权杖十",
            "name_en": "Ten of Wands",
            "upright": "重担、责任、压力、过度负荷、接近终点",
            "reversed": "放下包袱、学会委托、减轻负担、释放压力",
            "keywords": ["重压", "责任", "坚持到底"],
        },
        {
            "rank": "Page",
            "name": "权杖侍从",
            "name_en": "Page of Wands",
            "upright": "探索、热情、好奇心、新消息、冒险精神",
            "reversed": "缺乏方向、三分钟热度、轻率、延迟",
            "keywords": ["探索", "热情", "好奇"],
        },
        {
            "rank": "Knight",
            "name": "权杖骑士",
            "name_en": "Knight of Wands",
            "upright": "冲劲、冒险、充满活力、魅力、果断行动",
            "reversed": "冲动鲁莽、散漫、急躁、缺乏耐心",
            "keywords": ["冲劲", "冒险", "行动"],
        },
        {
            "rank": "Queen",
            "name": "权杖王后",
            "name_en": "Queen of Wands",
            "upright": "自信、魅力、热情、独立、社交能力",
            "reversed": "嫉妒、控制欲、自私、缺乏自信",
            "keywords": ["魅力", "自信", "热情"],
        },
        {
            "rank": "King",
            "name": "权杖国王",
            "name_en": "King of Wands",
            "upright": "领导力、远见、企业家精神、果断、鼓舞人心",
            "reversed": "专横、冲动决策、傲慢、期望过高",
            "keywords": ["领导", "远见", "果断"],
        },
    ],
    # ===== 圣杯 (Cups) - 水 =====
    "cups": [
        {
            "rank": "A",
            "name": "圣杯王牌",
            "name_en": "Ace of Cups",
            "upright": "新感情、爱的开始、情感充盈、直觉、灵性觉醒",
            "reversed": "情感压抑、封闭内心、爱被拒绝、自怜",
            "keywords": ["新感情", "情感涌现", "爱"],
        },
        {
            "rank": "2",
            "name": "圣杯二",
            "name_en": "Two of Cups",
            "upright": "伴侣关系、吸引力、合作、和谐、相互尊重",
            "reversed": "关系失衡、分离、信任破裂、沟通不畅",
            "keywords": ["关系", "连接", "平等"],
        },
        {
            "rank": "3",
            "name": "圣杯三",
            "name_en": "Three of Cups",
            "upright": "庆祝、友情、社交、团聚、共同欢乐",
            "reversed": "过度放纵、社交疲惫、八卦是非、孤立",
            "keywords": ["友情", "庆祝", "社交"],
        },
        {
            "rank": "4",
            "name": "圣杯四",
            "name_en": "Four of Cups",
            "upright": "冥想、不满足、冷漠、审视内心、错过机会",
            "reversed": "重新关注、接受新事物、走出冷漠、觉醒",
            "keywords": ["倦怠", "反思", "不满"],
        },
        {
            "rank": "5",
            "name": "圣杯五",
            "name_en": "Five of Cups",
            "upright": "失落、悲伤、遗憾、哀悼、聚焦于损失",
            "reversed": "走出悲伤、接受现实、释怀、发现新希望",
            "keywords": ["失落", "悲伤", "释怀"],
        },
        {
            "rank": "6",
            "name": "圣杯六",
            "name_en": "Six of Cups",
            "upright": "怀旧、纯真回忆、童年、重逢、善意",
            "reversed": "沉溺过去、无法前进、不切实际的怀旧",
            "keywords": ["怀旧", "纯真", "过去"],
        },
        {
            "rank": "7",
            "name": "圣杯七",
            "name_en": "Seven of Cups",
            "upright": "幻想、选择过多、白日梦、诱惑、想象力",
            "reversed": "脚踏实地、做出选择、认清现实、集中注意",
            "keywords": ["幻想", "选择", "迷惑"],
        },
        {
            "rank": "8",
            "name": "圣杯八",
            "name_en": "Eight of Cups",
            "upright": "放弃、离开、寻求更深意义、向前走、失望",
            "reversed": "害怕改变、留恋、漫无目的、逃避",
            "keywords": ["离开", "追寻", "放下"],
        },
        {
            "rank": "9",
            "name": "圣杯九",
            "name_en": "Nine of Cups",
            "upright": "心愿达成、满足、幸福感、享受成果、自信",
            "reversed": "贪婪、不满足、物质主义、表面快乐",
            "keywords": ["满足", "心愿", "幸福"],
        },
        {
            "rank": "10",
            "name": "圣杯十",
            "name_en": "Ten of Cups",
            "upright": "家庭幸福、圆满、情感满足、长久和谐、天伦之乐",
            "reversed": "家庭不和、期望落空、价值观分歧、不幸福",
            "keywords": ["圆满", "家庭", "和谐"],
        },
        {
            "rank": "Page",
            "name": "圣杯侍从",
            "name_en": "Page of Cups",
            "upright": "创意、直觉消息、浪漫信号、情感学习、敏感",
            "reversed": "情感不成熟、逃避感受、创意受阻、白日梦",
            "keywords": ["浪漫", "直觉", "创意"],
        },
        {
            "rank": "Knight",
            "name": "圣杯骑士",
            "name_en": "Knight of Cups",
            "upright": "浪漫追求、骑士精神、魅力、理想主义、提议",
            "reversed": "不切实际、情绪化、沉迷幻想、虚情假意",
            "keywords": ["浪漫", "追求", "理想"],
        },
        {
            "rank": "Queen",
            "name": "圣杯王后",
            "name_en": "Queen of Cups",
            "upright": "共情、直觉、温柔、情感成熟、关怀他人",
            "reversed": "情绪波动、过度敏感、依赖他人、牺牲自我",
            "keywords": ["共情", "温柔", "直觉"],
        },
        {
            "rank": "King",
            "name": "圣杯国王",
            "name_en": "King of Cups",
            "upright": "情感平衡、智慧、成熟、外交手腕、控制情绪",
            "reversed": "情绪操控、压抑感情、冷漠、喜怒无常",
            "keywords": ["情感智慧", "平衡", "成熟"],
        },
    ],
    # ===== 宝剑 (Swords) - 风 =====
    "swords": [
        {
            "rank": "A",
            "name": "宝剑王牌",
            "name_en": "Ace of Swords",
            "upright": "突破、真相、清晰、新想法、智力飞跃",
            "reversed": "混乱、误解、缺乏清晰度、破坏性想法",
            "keywords": ["真相", "突破", "清晰"],
        },
        {
            "rank": "2",
            "name": "宝剑二",
            "name_en": "Two of Swords",
            "upright": "两难抉择、僵局、逃避决定、需要平衡",
            "reversed": "信息浮现、做出选择、情感困惑、面对真相",
            "keywords": ["抉择", "僵局", "两难"],
        },
        {
            "rank": "3",
            "name": "宝剑三",
            "name_en": "Three of Swords",
            "upright": "心碎、悲伤、痛苦、分离、背叛",
            "reversed": "疗愈开始、释放痛苦、原谅、走出伤痛",
            "keywords": ["心碎", "悲伤", "释放"],
        },
        {
            "rank": "4",
            "name": "宝剑四",
            "name_en": "Four of Swords",
            "upright": "休息、恢复、冥想、退隐、充电",
            "reversed": "焦虑不安、过度疲劳、强撑、无法放松",
            "keywords": ["休息", "恢复", "静养"],
        },
        {
            "rank": "5",
            "name": "宝剑五",
            "name_en": "Five of Swords",
            "upright": "冲突、输赢分明、自私、背叛、算计",
            "reversed": "和解、认错、放下争执、收拾残局",
            "keywords": ["冲突", "得失", "教训"],
        },
        {
            "rank": "6",
            "name": "宝剑六",
            "name_en": "Six of Swords",
            "upright": "过渡、离开困境、转变、旅行、疗愈之旅",
            "reversed": "无法前行、旧事缠绕、抗拒改变、困在原地",
            "keywords": ["过渡", "离开", "前行"],
        },
        {
            "rank": "7",
            "name": "宝剑七",
            "name_en": "Seven of Swords",
            "upright": "策略、隐瞒、独自行动、智取、逃避",
            "reversed": "谎言被揭穿、良心不安、忏悔、被人识破",
            "keywords": ["策略", "隐瞒", "智谋"],
        },
        {
            "rank": "8",
            "name": "宝剑八",
            "name_en": "Eight of Swords",
            "upright": "被困、自我限制、无力感、受害者心态、焦虑",
            "reversed": "解放自我、看清出路、重获力量、打破限制",
            "keywords": ["束缚", "自困", "突破"],
        },
        {
            "rank": "9",
            "name": "宝剑九",
            "name_en": "Nine of Swords",
            "upright": "焦虑、噩梦、担忧、内疚、失眠",
            "reversed": "释放恐惧、走出阴影、寻求帮助、光明在前",
            "keywords": ["焦虑", "恐惧", "忧虑"],
        },
        {
            "rank": "10",
            "name": "宝剑十",
            "name_en": "Ten of Swords",
            "upright": "终结、最低谷、背叛、彻底结束、触底",
            "reversed": "触底反弹、最坏已过、恢复开始、不再抗拒",
            "keywords": ["终结", "触底", "新生"],
        },
        {
            "rank": "Page",
            "name": "宝剑侍从",
            "name_en": "Page of Swords",
            "upright": "好奇心、新想法、思维活跃、观察、求知欲",
            "reversed": "八卦、恶意中伤、思维混乱、欺骗",
            "keywords": ["好奇", "思辨", "观察"],
        },
        {
            "rank": "Knight",
            "name": "宝剑骑士",
            "name_en": "Knight of Swords",
            "upright": "果断行动、直言不讳、雄心勃勃、追求真相",
            "reversed": "冲动鲁莽、言辞伤人、缺乏同理心、横冲直撞",
            "keywords": ["果断", "直率", "进攻"],
        },
        {
            "rank": "Queen",
            "name": "宝剑王后",
            "name_en": "Queen of Swords",
            "upright": "独立思考、清晰沟通、公正客观、直觉与逻辑并用",
            "reversed": "冷酷无情、过于挑剔、封闭情感、尖酸刻薄",
            "keywords": ["理性", "独立", "清醒"],
        },
        {
            "rank": "King",
            "name": "宝剑国王",
            "name_en": "King of Swords",
            "upright": "权威、智慧、公正判断、纪律、理性决策",
            "reversed": "独裁、冷酷、滥用权力、操控他人",
            "keywords": ["智慧", "权威", "公正"],
        },
    ],
    # ===== 金币 (Pentacles) - 土 =====
    "pentacles": [
        {
            "rank": "A",
            "name": "金币王牌",
            "name_en": "Ace of Pentacles",
            "upright": "新财源、物质机遇、稳定基础、投资、繁荣开端",
            "reversed": "错失财运、计划落空、物质损失、贪婪",
            "keywords": ["财运", "机遇", "基础"],
        },
        {
            "rank": "2",
            "name": "金币二",
            "name_en": "Two of Pentacles",
            "upright": "平衡、灵活应变、多任务处理、适应变化、节制",
            "reversed": "失衡、分身乏术、财务混乱、顾此失彼",
            "keywords": ["平衡", "灵活", "应变"],
        },
        {
            "rank": "3",
            "name": "金币三",
            "name_en": "Three of Pentacles",
            "upright": "团队合作、精湛技艺、学习成长、被认可",
            "reversed": "缺乏协作、技艺不精、态度敷衍、被忽视",
            "keywords": ["合作", "技艺", "学习"],
        },
        {
            "rank": "4",
            "name": "金币四",
            "name_en": "Four of Pentacles",
            "upright": "守财、安全感、保守、控制、稳定",
            "reversed": "放开手脚、过度挥霍、失去安全感、吝啬",
            "keywords": ["守成", "安全", "控制"],
        },
        {
            "rank": "5",
            "name": "金币五",
            "name_en": "Five of Pentacles",
            "upright": "困难、贫穷、孤立、健康问题、缺乏支持",
            "reversed": "困境改善、找到帮助、恢复信心、渡过难关",
            "keywords": ["困难", "匮乏", "考验"],
        },
        {
            "rank": "6",
            "name": "金币六",
            "name_en": "Six of Pentacles",
            "upright": "慷慨、施与受、公平交换、慈善、物质帮助",
            "reversed": "附带条件的帮助、不平等、自私、债务",
            "keywords": ["慷慨", "给予", "平衡"],
        },
        {
            "rank": "7",
            "name": "金币七",
            "name_en": "Seven of Pentacles",
            "upright": "耐心等待、审视成果、长期投资、评估进展",
            "reversed": "缺乏耐心、回报不及预期、浪费努力、方向错误",
            "keywords": ["耐心", "收获", "评估"],
        },
        {
            "rank": "8",
            "name": "金币八",
            "name_en": "Eight of Pentacles",
            "upright": "勤奋、专注、技能提升、精雕细琢、学徒精神",
            "reversed": "敷衍了事、缺乏热情、重复无意义、完美主义",
            "keywords": ["勤奋", "精进", "专注"],
        },
        {
            "rank": "9",
            "name": "金币九",
            "name_en": "Nine of Pentacles",
            "upright": "独立富足、自给自足、享受成果、优雅生活、自律",
            "reversed": "过度依赖、财务不安全、表面光鲜、缺乏自律",
            "keywords": ["富足", "独立", "享受"],
        },
        {
            "rank": "10",
            "name": "金币十",
            "name_en": "Ten of Pentacles",
            "upright": "财富传承、家族兴旺、长久稳定、遗产、成就",
            "reversed": "家族纷争、遗产问题、财务纠纷、不稳定",
            "keywords": ["传承", "家业", "稳固"],
        },
        {
            "rank": "Page",
            "name": "金币侍从",
            "name_en": "Page of Pentacles",
            "upright": "务实学习、新技能、财务规划、脚踏实地",
            "reversed": "好高骛远、缺乏实际、浪费机会、懒散",
            "keywords": ["学习", "务实", "规划"],
        },
        {
            "rank": "Knight",
            "name": "金币骑士",
            "name_en": "Knight of Pentacles",
            "upright": "稳重可靠、勤劳踏实、有责任心、坚持不懈",
            "reversed": "固执保守、无趣、过于缓慢、缺乏远见",
            "keywords": ["踏实", "可靠", "坚持"],
        },
        {
            "rank": "Queen",
            "name": "金币王后",
            "name_en": "Queen of Pentacles",
            "upright": "实际关怀、财务智慧、温暖家庭、滋养他人、安全感",
            "reversed": "过度操心、忽视自我、物质焦虑、控制家庭",
            "keywords": ["关怀", "务实", "安稳"],
        },
        {
            "rank": "King",
            "name": "金币国王",
            "name_en": "King of Pentacles",
            "upright": "财富、商业成功、安全稳定、慷慨、实际领导力",
            "reversed": "贪婪、投机、工作狂、物质至上、固步自封",
            "keywords": ["财富", "成功", "稳健"],
        },
    ],
}
