"""add_payment_orders_and_agent_workflows_tables

Revision ID: 2128b2952e1b
Revises: 6ed00bd93a71
Create Date: 2026-04-02 15:07:41.244578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2128b2952e1b'
down_revision: Union[str, Sequence[str], None] = '6ed00bd93a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_workflows',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_workflows_agent_id', 'agent_workflows', ['agent_id'], unique=False)
    op.create_index('idx_agent_workflows_tenant_id', 'agent_workflows', ['tenant_id'], unique=False)

    op.create_table('payment_orders',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_orders_tenant_id', 'payment_orders', ['tenant_id'], unique=False)
    op.create_index('idx_payment_orders_status', 'payment_orders', ['status'], unique=False)
    op.create_index('idx_payment_orders_order_no', 'payment_orders', ['order_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_orders_order_no', table_name='payment_orders')
    op.drop_index('idx_payment_orders_status', table_name='payment_orders')
    op.drop_index('idx_payment_orders_tenant_id', table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('idx_agent_workflows_tenant_id', table_name='agent_workflows')
    op.drop_index('idx_agent_workflows_agent_id', table_name='agent_workflows')
    op.drop_table('agent_workflows')
    # ### end Alembic commands ###
