"""add_wechat_openid_unionid_to_users

Revision ID: 45cb1562bcf6
Revises: d67437741adf
Create Date: 2026-04-07 15:06:41.265647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cb1562bcf6'
down_revision: Union[str, Sequence[str], None] = 'd67437741adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wechat_openid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('wechat_unionid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.drop_column('users', 'wechat_unionid')
    op.drop_column('users', 'wechat_openid')
    # ### end Alembic commands ###
