"""initial_schema

Revision ID: 841408804e57
Revises: 58d863772b1a
Create Date: 2026-04-02 00:41:40.102002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841408804e57'
down_revision: Union[str, Sequence[str], None] = '58d863772b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        nullable=False, server_default=sa.text('now()'),
    ))
    op.alter_column('knowledge_chunks', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'updated_at')
    # ### end Alembic commands ###
