"""add_storage_key_to_knowledge_documents

Revision ID: d67437741adf
Revises: a3f1c9d82e4b
Create Date: 2026-04-07 10:59:57.062768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67437741adf'
down_revision: Union[str, Sequence[str], None] = 'a3f1c9d82e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('storage_key', sa.String(length=1024), nullable=True, comment='MinIO object key'))
    op.create_unique_constraint(None, 'payment_orders', ['order_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_orders', type_='unique')
    op.drop_column('knowledge_documents', 'storage_key')
    # ### end Alembic commands ###
